# Generated by Django 5.1.5 on 2025-02-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('haqida', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name_plural': 'Bolimlar',
            },
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=120)),
                ('tirik', models.BooleanField(default=False)),
                ('davlat', models.CharField(max_length=133)),
            ],
            options={
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=111)),
                ('yili', models.DateField()),
                ('file', models.FileField(upload_to='')),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.bolim')),
                ('muallif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.muallif')),
            ],
            options={
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
